SELECT 'Hello World!' as msg;

SELECT 2 + 2 AS operation;
SELECT 2 * 2 AS operation;

SELECT NOT FALSE AS operation UNION ALL # 1
SELECT NOT TRUE UNION ALL				# 0
SELECT TRUE OR FALSE UNION ALL			# 1
SELECT TRUE AND FALSE;					# 0

SELECT 1 = 1 AS COMPARACAO_NUMERO UNION ALL 	# 1
SELECT 1 >= 1 UNION ALL 						# 1
SELECT 1 <= 1 UNION ALL 						# 1
SELECT 2 != 1 UNION ALL							# 1
SELECT 2 > 1 UNION ALL							# 1
SELECT 1 < 2;									# 1


SELECT 'A' = 'A' AS COMPARACAO_STRING UNION ALL
SELECT 'A' >= 'A' UNION ALL 						# 1
SELECT 'A' <= 'A' UNION ALL 						# 1
SELECT 'A' != 'B' UNION ALL							# 1
SELECT 'A' < 'B' UNION ALL							# 1
SELECT 'B' > 'A';									# 1

## Funções de Data

SELECT CURRENT_TIMESTAMP(), CURRENT_DATE(), CURRENT_TIME();

SELECT CURRENT_DATE() AS HOJE, DATE_ADD(CURRENT_DATE(), INTERVAL 1 DAY) AS RESULT UNION ALL
SELECT CURRENT_DATE(), DATE_ADD(CURRENT_DATE(), INTERVAL 1 MONTH) UNION ALL
SELECT CURRENT_DATE(), DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) UNION ALL
SELECT CURRENT_DATE(), DATE_SUB(CURRENT_DATE(), INTERVAL 1 MONTH);

SELECT DATE_FORMAT(CURRENT_TIMESTAMP(), '%y-%m-%d');

SELECT CONVERT(23.2, INT(2));