version: '3'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass_123
      MYSQL_DATABASE: learn
    volumes:
      - /opt/mysql_data:/var/lib/mysql

  postgres:
    image: postgres
    restart: always
    ports:
      - 35432:5432
    environment:
      POSTGRES_PASSWORD: pass_123
    volumes:
      - /opt/postgres_data:/var/lib/postgresql/data 

