version: '3'

services:

  # MySQL
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass_123
      MYSQL_DATABASE: learn
    volumes:
      - /opt/mysql_data:/var/lib/mysql
    networks:
      - databases-net

    # PostgreSQL
  postgres_1:
    image: postgres
    container_name: my-postgres-1
    restart: always
    ports:
      - 35432:5432
    environment:
      POSTGRES_PASSWORD: pass_123
    volumes:
      - /opt/postgres_data_sharding_1:/var/lib/postgresql/data 
    networks:
      - databases-net

  postgres_2:
    image: postgres
    container_name: my-postgres-2
    restart: always
    ports:
      - 35433:5432
    environment:
      POSTGRES_PASSWORD: pass_123
    volumes:
      - /opt/postgres_data_sharding_2:/var/lib/postgresql/data 
    networks:
      - databases-net

  postgres_3:
    image: postgres
    container_name: my-postgres-3
    restart: always
    ports:
      - 35434:5432
    environment:
      POSTGRES_PASSWORD: pass_123
    volumes:
      - /opt/postgres_data_3:/var/lib/postgresql/data 
    networks:
      - databases-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: marco@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pass_123
    networks:
      - databases-net

  #################################    NOSQL    ###############################################
  ### MongoDB
  mongo:
    image: mongo
    container_name: my-mongo
    restart: always
    volumes:
      - /data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dadaia_123
    networks:
      - databases-net

  mongo-express:
    image: mongo-express
    container_name: my-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: dadaia_123
      ME_CONFIG_MONGODB_URL: mongodb://root:dadaia_123@mongo:27017/
    links:
      - mongo
    networks:
      - databases-net
    depends_on:
      - mongo

networks:
  databases-net:
    driver: bridge