version: '3'

x-common-settings: &postgres-base

  restart: always
  networks:
    - databases-net

services:


  cassandra-node1:
    image: cassandra:latest

    ports:
      - "9042:9042"
    container_name: cassandra-node1
    environment:
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_CLUSTER_NAME=mycasscluster

  cassandra-node2:
    image: cassandra:latest
    container_name: cassandra-node2
    ports:
      - "9043:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_CLUSTER_NAME=mycasscluster

  cassandra-node3:
    image: cassandra:latest
    container_name: cassandra-node3
    ports:
      - "9044:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_CLUSTER_NAME=mycasscluster
