version: '3'

x-common-settings: &mysql-base
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: mysql
    MYSQL_DATABASE: mysql_learning
  networks:
    - databases-net

services:
  mysql:
    build: ./docker/mysql
    <<: *mysql-base
    container_name: dadaia-mysql
    ports:
      - 3306:3306

  mysql_sharding_1:
    image: mysql
    <<: *mysql-base
    container_name: dadaia_mysql_sharding_1
    ports:
      - 13306:3306

  mysql_sharding_2:
    image: mysql
    <<: *mysql-base
    container_name: dadaia_mysql_sharding_2
    ports:
      - 13307:3306

  mysql_sharding_3:
    image: mysql
    <<: *mysql-base
    container_name: dadaia_mysql_sharding_3
    ports:
      - 13308:3306

  adminer:
    image: adminer
    container_name: dadaia-adminer
    restart: always
    ports:
      - 18080:8080
    networks:
      - databases-net

networks:
  databases-net:
    driver: bridge