USE vendas_sucos;

CREATE TABLE tab_padrao
(ID INT AUTO_INCREMENT,
DESCRITOR VARCHAR(20),
ENDERECO VARCHAR (100) NULL,
CIDADE VARCHAR(50) DEFAULT 'Rio de Janeiro',
DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
PRIMARY KEY(ID));

INSERT INTO tab_padrao (DESCRITOR, ENDERECO, CIDADE, DATA_CRIACAO)
VALUES ('cliente_x', 'R. das Margaridas', 'Inhaúma', '2022-10-12');


INSERT INTO tab_padrao (DESCRITOR) VALUES ('cliente_y');

SELECT * FROM tab_padrao;

